# Generated by Django 5.0.1 on 2024-01-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_app_created_at_subscription_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="app",
            name="plan",
        ),
    ]
